package com.linkedin.poststudio.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FormattingOperation {
    // We use a String for ID instead of UUID as it's simpler for JSON serialization
    // and can be generated by the frontend if needed, but usually generated by backend/AI.
    private String id;
    
    // "style" or "list"
    private String type;
    
    // Character indices in the original source text
    private int start;
    private int end;
    
    // Used when type == "style" (bold, italic, underline, strikethrough, boldItalic)
    private String style;
    
    // Used when type == "list" (dot, arrow, number)
    private String marker;
}
